#!/bin/sh
set -e

SHLIB_CALL_APPLETS="
atomic_file_counter
charwise
dir_empty
dir_not_empty
dodir
external_ip
get_yn
host_alive
sleeploop
str_lstrip str_rstrip str_strip str_trim
"

# modules required by vdr-recordmux and provided by the "all" library
VDR_RECORDMUX_DEPENDS="
fs/dodir
fs/level
function/defined
list_has
logging
message
readconfig
varcheck
"

SET_DEFAULTS
SET_BASH n /bin/bash

INTO /tv

ENABLE_OVERWRITE_IF lib/shlib.sh

MAKELIB_SHLIB

INHERIT shlib-call

# liram-manage
#  currently, all of its dependencies are covered by the "shlib"/"all" lib
LINK_SHARED liram-manage root/liram-manage
DEST_PREFIX root SYMSTORM liram-manage liram-pack liram-fixup liram-kernup

# standalone scripts
#
for s in fs/disk_id fs/get_user_tmpdir; do
   STANDALONE "${s}" "${s##*/}"
done

# create some linked scripts
#
for l in \
   hardware_policy \
   fs/md_each \
   net-misc/get_blocklist net-misc/transmission_update_blocklist
do
   LINK_SHARED "${l}" "${l##*/}"
done

# Create a "difference" lib for vdr-recordmux (explicitly exclude modules
# provided by the "all" lib) and append the vdr-recordmux script.
#
# TODO: This could also be solved via STANDALONE().
#
SPLITLIB vdr/recordmux vdr-recordmux ${VDR_RECORDMUX_DEPENDS?}
SPLITLIB_APPEND vdr/recordmux vdr-recordmux.sh
CHMOD 0755

# chmod multicall script into lib/
SRC_PREFIX lib DOLIB chmod sudofy_script
SYMSTORM lib/chmod.sh -r +r +w -w +x -x

# remount multicall script into root/lib/
SRC_PREFIX lib DOLIB_ROOT remount pack_system
DEST_PREFIX root SYMSTORM lib/remount.sh rootfs-ro rootfs-rw

# include local build instructions if requested to do so
#
#  These are mainly (a) scripts that dont use shlib at all, not necessarily
#  written in *sh, and (b) scripts not released yet.
#
if use local; then
   INHERIT_LOCAL
else
   PRINT "Not building local scripts due to USE=\"-local\""
fi
