#!/bin/sh
__prjroot="${0%/*}"
__name="${0##*/}"
__script="${__prjroot}/build-scripts/${__name%.sh}.sh"

export SHLIB_PRJROOT="${__prjroot}"

if [ ! -f "${__script}" ]; then
   echo "script not found: ${__script}" 1>&2
   exit 9
fi

if [ -e "${__prjroot}/runscript-static" ]; then
   exec "${__prjroot}/runscript-static" "${__script}" "$@"
elif [ -e "${__prjroot}/runscript" ]; then
   exec "/bin/bash" "${__prjroot}/runscript" "${__script}" "$@"
else
   echo "no runscript wrapper found!" 1>&2
   exit 10
fi
