#!/bin/sh
if which shlibcc 1>/dev/null 2>/dev/null; then
	CC=shlibcc
elif [ -x ../shlibcc/shlibcc.py ]; then
	CC=../shlibcc/shlibcc.py
else
	echo "cannot locate shlibcc" 1>&2
	exit 2
fi

run() { echo "$*"; "$@"; }
run "${CC}" -S ${0%/*}/lib "$@"
